version: "3.3"

services:
  db_primary:
    build: .
    container_name: "primary"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=test_user
      - POSTGRESQL_REPLICATION_PASSWORD=my-secret-passwd
      - POSTGRESQL_POSTGRES_PASSWORD=my-secret-passwd
      - POSTGRESQL_DATABASE=tap_postgres_test
      - POSTGRESQL_WAL_LEVEL=logical
      - ALLOW_EMPTY_PASSWORD=yes
  db_replica:
    image: "docker.io/bitnami/postgresql:12"
    container_name: replica
    ports:
      - "5433:5432"
    depends_on:
      - db_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=test_user
      - POSTGRESQL_REPLICATION_PASSWORD=my-secret-passwd
      - POSTGRESQL_MASTER_HOST=db_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
