name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: circleci/python:3.6.2
      env:
        TAP_POSTGRES_PORT: 5432
        TAP_POSTGRES_USER: test_user
        TAP_POSTGRES_PASSWORD: my-secret-passwd
        TAP_POSTGRES_HOST: test_postgres

    services:
      test_postgres:
        image: postgres:12
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: my-secret-passwd
          POSTGRES_DB: tap_postgres_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup virtual environment
        run: make venv

      - name: Pylinting
        run: make pylint

      - name: Tests
        env:
          LOGGING_CONF_FILE: ./sample_logging.conf
        run: make test
