name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]

    services:
      test_postgres:
        image: postgres:12
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: my-secret-passwd
          POSTGRES_DB: tap_postgres_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.container[1] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup virtual environment
        run: make venv

      - name: Pylinting
        run: make pylint

      - name: Tests
        env:
          TAP_POSTGRES_PORT: 5432
          TAP_POSTGRES_USER: test_user
          TAP_POSTGRES_PASSWORD: my-secret-passwd
          TAP_POSTGRES_HOST: localhost
          LOGGING_CONF_FILE: ./sample_logging.conf
        run: make test
